# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gets the Random Numbers
#'
#' @param nTry number of observations
#' @param seed seed to configure RNG
#' @param k DX parameter
#' @return nTry random numbers
rand_test <- function(nTry, seed, k) {
    .Call(`_DX_generator_rand_test`, nTry, seed, k)
}

